import React, { createContext, useState } from "react";
export const ProductContext = createContext();
const mirrors = [
  {
    id: 13,
    name: "Дзеркало MARSTAL д.70см чорний",
    subCategoryName: "Дзеркала",
    price: 1500,
    imageUrl: require("../../assets/bedroom/mirrors/mirrors1.jpg"),
    checked: false,
  },
  {
    id: 14,
    name: "Дзеркало BALSLEV 35x127см білий",
    subCategoryName: "Дзеркала",
    price: 1000,
    imageUrl: require("../../assets/bedroom/mirrors/mirrors2.jpg"),
    checked: false,
  },
  {
    id: 15,
    name: "Дзеркало SPANG 40x70см чорний",
    subCategoryName: "Дзеркала",
    price: 1000,
    imageUrl: require("../../assets/bedroom/mirrors/mirrors3.jpg"),
    checked: false,
  },
  {
    id: 16,
    name: "Дзеркало NORDBORG 72х162см золотистий",
    subCategoryName: "Дзеркала",
    price: 1750,
    imageUrl: require("../../assets/bedroom/mirrors/mirrors4.jpg"),
    checked: false,
  },
  {
    id: 17,
    name: "Дзеркало STUDSTRUP 80x180см чорний",
    subCategoryName: "Дзеркала",
    price: 5000,
    imageUrl: require("../../assets/bedroom/mirrors/mirrors5.jpg"),
    checked: false,
  },
];
const wardrobes = [
  {
    id: 18,
    name: "Шафа HAGENDRUP 96x176см комбі білий",
    subCategoryName: "Шафи",
    price: 5500,
    imageUrl: require("../../assets/bedroom/wardrobes/wardrobes1.jpg"),
    checked: false,
  },
  {
    id: 19,
    name: "Шафа HAGENDRUP 3дв 3шух дуб",
    subCategoryName: "Шафи",
    price: 7500,
    imageUrl: require("../../assets/bedroom/wardrobes/wardrobes2.jpg"),
    checked: false,
  },
  {
    id: 20,
    name: "Шафа BILLUND 2дв 2шух білий/бетон",
    subCategoryName: "Шафи",
    price: 5500,
    imageUrl: require("../../assets/bedroom/wardrobes/wardrobes3.jpg"),
    checked: false,
  },
  {
    id: 21,
    name: "Шафа JENSLEV 145x176см дуб",
    subCategoryName: "Шафи",
    price: 8500,
    imageUrl: require("../../assets/bedroom/wardrobes/wardrobes4.jpg"),
    checked: false,
  },
  {
    id: 22,
    name: "Шафа VELLERUP 200х200см комбі дуб",
    subCategoryName: "Шафи",
    price: 13500,
    imageUrl: require("../../assets/bedroom/wardrobes/wardrobes5.jpg"),
    checked: false,
  },
];

const shelves = [
  {
    id: 47,
    name: "Стелаж VANDBORG 3пол дуб/чорний",
    subCategoryName: "Книжкові шафи",
    price: 1750,
    imageUrl: require("../../assets/office/shelves/shelves1.jpg"),
    checked: false,
  },
  {
    id: 48,
    name: "Стелаж TRAPPEDAL 5пол дуб/білий",
    subCategoryName: "Книжкові шафи",
    price: 2350,
    imageUrl: require("../../assets/office/shelves/shelves2.jpg"),
    checked: false,
  },
  {
    id: 49,
    name: "Шафка SKALS 2дв дуб",
    subCategoryName: "Книжкові шафи",
    price: 3000,
    imageUrl: require("../../assets/office/shelves/shelves3.jpg"),
    checked: false,
  },
  {
    id: 50,
    name: "Шафка SKALS 2дв білий",
    subCategoryName: "Книжкові шафи",
    price: 2750,
    imageUrl: require("../../assets/office/shelves/shelves4.jpg"),
    checked: false,
  },
];
const chairs = [
  {
    id: 51,
    name: "Стілець обідній JONSTRUP сірий/дуб",
    subCategoryName: "Стільці",
    price: 1350,
    imageUrl: require("../../assets/diningroom/chairs/chair1.jpg"),
    checked: false,
  },
  {
    id: 52,
    name: "Стілець обідній EJSTRUP синій/сталь",
    subCategoryName: "Стільці",
    price: 1650,
    imageUrl: require("../../assets/diningroom/chairs/chair2.jpg"),
    checked: false,
  },
  {
    id: 53,
    name: "Стілець обідній TUREBY беж тканина",
    subCategoryName: "Стільці",
    price: 2000,
    imageUrl: require("../../assets/diningroom/chairs/chair3.jpg"),
    checked: false,
  },
  {
    id: 54,
    name: "Стілець обідній KOKKEDAL сірий/дуб",
    subCategoryName: "Стільці",
    price: 1850,
    imageUrl: require("../../assets/diningroom/chairs/chair4.jpg"),
    checked: false,
  },
  {
    id: 55,
    name: "Стілець обідній TOREBY шт.шкіра чорний",
    subCategoryName: "Стільці",
    price: 1000,
    imageUrl: require("../../assets/diningroom/chairs/chair5.jpg"),
    checked: false,
  },
  {
    id: 56,
    name: "Стілець обідній GADSTRUP чорний дуб",
    subCategoryName: "Стільці",
    price: 1000,
    imageUrl: require("../../assets/diningroom/chairs/chair6.jpg"),
    checked: false,
  },
  {
    id: 57,
    name: "Стілець обідній TYLSTRUP кавовий",
    subCategoryName: "Стільці",
    price: 1350,
    imageUrl: require("../../assets/diningroom/chairs/chair7.jpg"),
    checked: false,
  },
  {
    id: 58,
    name: "Стілець обідній JEGIND натура/білий",
    subCategoryName: "Стільці",
    price: 2000,
    imageUrl: require("../../assets/diningroom/chairs/chair8.jpg"),
    checked: false,
  },
];
const buffets = [
  {
    id: 67,
    name: "Буфет JENSLEV 2дв 4шух дуб/білий",
    subCategoryName: "Буфети",
    price: 5000,
    imageUrl: require("../../assets/livingroom/buffets/buffets1.jpg"),
    checked: false,
  },
  {
    id: 68,
    name: "Буфет SKOVLUNDE 2дв 3шух натур. дуб/чорний",
    subCategoryName: "Буфети",
    price: 9000,
    imageUrl: require("../../assets/livingroom/buffets/buffets2.jpg"),
    checked: false,
  },
  {
    id: 69,
    name: "Буфет-сервант MARKSKEL білий/дуб",
    subCategoryName: "Буфети",
    price: 21998,
    imageUrl: require("../../assets/livingroom/buffets/buffets3.jpg"),
    checked: false,
  },
  {
    id: 70,
    name: "Буфет MANDERUP 3дв 3шух дикий дуб",
    subCategoryName: "Буфети",
    price: 11999,
    imageUrl: require("../../assets/livingroom/buffets/buffets4.jpg"),
    checked: false,
  },
];
const productState = {
  lastId: 112,
  bedroom: {
    categoryName: "Спальня",
    categoryTitle:
      "Великий вибір меблів для спальні та інтер'єру кімнати: матраци, ковдри, подушки та постільна білизна",
    categoryDescription:
      "Безперечно, спальня – кімната, де людина проводить значну частину свого часу. Ліжко, своєю чергою, важливий предмет спальної кімнати, місце, де ми відпочиваємо та відновлюємо сили. Ліжко відіграє значну роль у житті людини, а тому, неабиякої важливості набуває правильний вибір ліжка, яке відповідатиме потребам і стилю життя людини. Спальна кімната має бути місцем, яке налаштовує нас на відпочинок, тому важливо, щоб дизайн і комфорт органічно поєднувалися та доповнювали одне одного. Ми можемо запропонувати вам недорого купити спальні гарнітури, підібрати комплект з однієї серії меблів, або ж ви можете вибрати тільки ліжко, тумби чи шафу. Матрац, ковдра, подушка, покривало, комплект постільної білизни чи пледи – комплексне рішення для вашого здорового сну.",
    imageUrl: require("../../assets/bedroom/bedroom.jpg"),
    accessories: [
      {
        id: 1,
        name: "Ніжки для ламельної основи 4шт. д.5см в.23см сталь",
        subCategoryName: "Аксесуари",
        price: 400,
        imageUrl: require("../../assets/bedroom/accessories/accessories1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Вставка між матрацами д.195см DREAMZONE",
        subCategoryName: "Аксесуари",
        price: 500,
        imageUrl: require("../../assets/bedroom/accessories/accessories2.jpg"),
        checked: false,
      },
    ],
    beds: [
      {
        id: 3,
        name: "Ліжко KILDEN 90x200см темно-сірий",
        subCategoryName: "Ліжка",
        price: 4500,
        imageUrl: require("../../assets/bedroom/beds/beds1.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Ліжко SALLINGE 140x200см натура",
        subCategoryName: "Ліжка",
        price: 5250,
        imageUrl: require("../../assets/bedroom/beds/beds2.jpg"),
        checked: false,
      },
      {
        id: 5,
        name: "Ліжко VEDDE 140x200см дикий дуб",
        subCategoryName: "Ліжка",
        price: 6250,
        imageUrl: require("../../assets/bedroom/beds/beds3.jpg"),
        checked: false,
      },
      {
        id: 6,
        name: "Ліжко KONGSBERG 140x200см сірий",
        subCategoryName: "Ліжка",
        price: 8000,
        imageUrl: require("../../assets/bedroom/beds/beds4.jpg"),
        checked: false,
      },
      {
        id: 7,
        name: "Ліжко HASLEV 140x200см т.сірий",
        subCategoryName: "Ліжка",
        price: 11500,
        imageUrl: require("../../assets/bedroom/beds/beds5.jpg"),
        checked: false,
      },
    ],
    pillows: [
      {
        id: 8,
        name: "Подушка BEITO 50x70см 850г",
        subCategoryName: "Подушки",
        price: 1100,
        imageUrl: require("../../assets/bedroom/pillows/pillows1.jpg"),
        checked: false,
      },
      {
        id: 9,
        name: "Подушка ROMEDAL 50x70см 900г",
        subCategoryName: "Подушки",
        price: 375,
        imageUrl: require("../../assets/bedroom/pillows/pillows2.jpg"),
        checked: false,
      },
      {
        id: 10,
        name: "Подушка ROMEDAL висока 50x70см 1100г",
        subCategoryName: "Подушки",
        price: 550,
        imageUrl: require("../../assets/bedroom/pillows/pillows3.jpg"),
        checked: false,
      },
      {
        id: 11,
        name: "Подушка STEINKOLLEN 50х70см 1050г",
        subCategoryName: "Подушки",
        price: 400,
        imageUrl: require("../../assets/bedroom/pillows/pillows4.jpg"),
        checked: false,
      },
      {
        id: 12,
        name: "Подушка FALKETIND 750г 50x70см",
        subCategoryName: "Подушки",
        price: 850,
        imageUrl: require("../../assets/bedroom/pillows/pillows5.jpg"),
        checked: false,
      },
    ],
    mirrors: [...mirrors],
    wardrobes: [...wardrobes],
    //add more sub categories
  },
  bathroom: {
    categoryName: "Ванна",
    categoryTitle: "Все для облаштування ванної кімнати",
    categoryDescription:
      "Пухнасті махрові рушники та халати, м'які килимки, які можна покласти біля ванни, під умивальник та унітаз, стильні занавіски та, навіть, домашні капці - ми зробимо з вашої ванної територію СПА відпочинку! Тут ви знайдете все, що знадобиться для перетворення вашої ванної кімнати у приємну зону відпочинку та догляду за собою. Прикрасьте ванну килимками, кошиками та іншими аксесуарами – все це у нас є, ще й за доступними цінами та з постійними знижками! Дизайн ванної кімнати залежить від найменших дрібниць та стильних аксесуарів. Кольорові рушники для всієї сім'ї та різноманітні аксесуари створюють ваш власний дизайн. Наприклад, родзинкою може стати новинка в асортименті - скляна шкатулка для прикрас із серії неймовірно стильних аксесуарів для ванни. Якщо ви шукаєте універсальний подарунок - якісний текстиль та стильні аксесуари завжди стануть у пригоді.",
    imageUrl: require("../../assets/bathroom/bathroom.jpg"),
    accessories: [
      {
        id: 23,
        name: "Склянка для щіток ESSVIK перероблене скло",
        subCategoryName: "Аксесуари",
        price: 115,
        imageUrl: require("../../assets/bathroom/accessories/accessories1.jpg"),
        checked: false,
      },
      {
        id: 24,
        name: "Відро VEGBY 5 л морські водорості",
        subCategoryName: "Аксесуари",
        price: 700,
        imageUrl: require("../../assets/bathroom/accessories/accessories2.jpg"),
        checked: false,
      },
      {
        id: 25,
        name: "Полиця NACKA з гачками чорний",
        subCategoryName: "Аксесуари",
        price: 800,
        imageUrl: require("../../assets/bathroom/accessories/accessories3.jpg"),
        checked: false,
      },
      {
        id: 26,
        name: "Диспенсер для мила ROSENLUND асорт.",
        subCategoryName: "Аксесуари",
        price: 90,
        imageUrl: require("../../assets/bathroom/accessories/accessories4.jpg"),
        checked: false,
      },
    ],
    towels: [
      {
        id: 27,
        name: "Рушник FLISBY 40x60см білий",
        subCategoryName: "Рушники",
        price: 35,
        imageUrl: require("../../assets/bathroom/towels/towels1.jpg"),
        checked: false,
      },
      {
        id: 28,
        name: "Рушник TORSBY 50x90см сірий",
        subCategoryName: "Рушники",
        price: 100,
        imageUrl: require("../../assets/bathroom/towels/towels2.jpg"),
        checked: false,
      },
      {
        id: 29,
        name: "Рушник YSBY 50x90см рожевий",
        subCategoryName: "Рушники",
        price: 135,
        imageUrl: require("../../assets/bathroom/towels/towels3.jpg"),
        checked: false,
      },
      {
        id: 30,
        name: "Рушник MALUNG 50x100см беж",
        subCategoryName: "Рушники",
        price: 160,
        imageUrl: require("../../assets/bathroom/towels/towels4.jpg"),
        checked: false,
      },
    ],
    mirrors: [...mirrors],
    bathrobes: [
      {
        id: 31,
        name: "Халат NITTA S/M мікрофібра білий",
        subCategoryName: "Халати та капці",
        price: 550,
        imageUrl: require("../../assets/bathroom/bathrobes/bathrobes1.jpg"),
        checked: false,
      },
      {
        id: 32,
        name: "Халат VALBO L/XL т.синій",
        subCategoryName: "Халати та капці",
        price: 500,
        imageUrl: require("../../assets/bathroom/bathrobes/bathrobes2.jpg"),
        checked: false,
      },
      {
        id: 33,
        name: "Капці BROKIND р.36-46 в асортименті",
        subCategoryName: "Халати та капці",
        price: 450,
        imageUrl: require("../../assets/bathroom/bathrobes/bathrobes3.jpg"),
        checked: false,
      },
      {
        id: 34,
        name: "Сандалі LAXVIK 35-42 асорт.",
        subCategoryName: "Халати та капці",
        price: 475,
        imageUrl: require("../../assets/bathroom/bathrobes/bathrobes4.jpg"),
        checked: false,
      },
    ],
    //add more sub categories
  },
  office: {
    categoryName: "Офіс",
    categoryTitle:
      "Офісні меблі для робочого кабінету, офісу, шкільної або робочої зони вдома",
    categoryDescription:
      "Не важливо, де ви працюєте – в офісі чи вдома. Головне, щоб атмосфера сприяла продуктивній діяльності. Звертайтеся до нас – ми допоможемо створити комфортне місце для праці. У наших магазинах та на сайті є письмові, комп'ютерні та робочі столи, станції для ПК, підставки для ноутбуків та офісні стільці – і все пропонується за дуже привабливими цінами. Облаштувати робочу зону вдома просто! Столи з нашого асортименту здебільшого мають компактний розмір та підходять для найменших кімнат, балконів та куточків. Офісний стілець або крісло на коліщатах можна вибрати за власними вподобаннями – різні матеріали, форми та завжди максимальна підтримка спини. Додайте сучасне освітлення, килимок для крісла та полицю для зручного зберігання й домашній офіс готовий!",
    imageUrl: require("../../assets/office/office.jpg"),
    accessories: [
      {
        id: 35,
        name: "Підставка для ноутбука THEM бамбук",
        subCategoryName: "Аксесуари",
        price: 1000,
        imageUrl: require("../../assets/office/accessories/accessories1.jpg"),
        checked: false,
      },
      {
        id: 36,
        name: "Підставка для ноутбука MEJLBY регульована чорний",
        subCategoryName: "Аксесуари",
        price: 750,
        imageUrl: require("../../assets/office/accessories/accessories2.jpg"),
        checked: false,
      },
      {
        id: 37,
        name: "Підставка для ноутбука NEJRUP асорт.",
        subCategoryName: "Аксесуари",
        price: 450,
        imageUrl: require("../../assets/office/accessories/accessories3.jpg"),
        checked: false,
      },
      {
        id: 38,
        name: "Підставка для монітора SULDRUP чорний",
        subCategoryName: "Аксесуари",
        price: 700,
        imageUrl: require("../../assets/office/accessories/accessories4.jpg"),
        checked: false,
      },
    ],
    officeChairs: [
      {
        id: 39,
        name: "Крісло офісне BILLUM чорний",
        subCategoryName: "Крісла офісні",
        price: 2650,
        imageUrl: require("../../assets/office/chairs/chairs1.jpg"),
        checked: false,
      },
      {
        id: 40,
        name: "Крісло офісне SKODSBORG сірий",
        subCategoryName: "Крісла офісні",
        price: 4000,
        imageUrl: require("../../assets/office/chairs/chairs2.jpg"),
        checked: false,
      },
      {
        id: 41,
        name: "Крісло офісне KASTBJERG шт.шкіра чорний",
        subCategoryName: "Крісла офісні",
        price: 5500,
        imageUrl: require("../../assets/office/chairs/chairs3.jpg"),
        checked: false,
      },
      {
        id: 42,
        name: "Крісло офісне ABILDHOLT т.сірий/хром",
        subCategoryName: "Крісла офісні",
        price: 2650,
        imageUrl: require("../../assets/office/chairs/chairs4.jpg"),
        checked: false,
      },
    ],
    tables: [
      {
        id: 43,
        name: "Стіл письмовий VANDBORG 60х120 дуб/чорн.",
        subCategoryName: "Письмові столи",
        price: 1500,
        imageUrl: require("../../assets/office/tables/tables1.jpg"),
        checked: false,
      },
      {
        id: 44,
        name: "Стіл геймерський HALSTED 60х120см чорний",
        subCategoryName: "Письмові столи",
        price: 2250,
        imageUrl: require("../../assets/office/tables/tables2.jpg"),
        checked: false,
      },
      {
        id: 45,
        name: "Стіл письмовий BILLUND 53х120 білий/дуб",
        subCategoryName: "Письмові столи",
        price: 3000,
        imageUrl: require("../../assets/office/tables/tables3.jpg"),
        checked: false,
      },
      {
        id: 46,
        name: "Стіл письмовий EVETOFTE дуб",
        subCategoryName: "Письмові столи",
        price: 3750,
        imageUrl: require("../../assets/office/tables/tables4.jpg"),
        checked: false,
      },
    ],
    shelves: [...shelves],
    //add more sub categories
  },
  livingroom: {
    categoryName: "Вітальня",
    categoryTitle:
      "Сучасні меблі для оселі – все, що потрібно для облаштування вітальні",
    categoryDescription:
      "Вітальня у квартирі чи будинку – кімната багатофункціональна. Це місце, яке можна зробити по-справжньому своїм, неповторним. Дизайн вітальної кімнати повинен бути стильним та функціональним. У сучасному світі навіть у маленькій кімнаті можна створити ергономічний простір для відпочинку, роботи та сімейних обідів. Це досягається шляхом оформлення кімнати у світлих тонах з додаванням яскравих акцентів, зонування та вибору ергономічних меблів. Наш меблевий асортимент складається з модульних систем, завдяки чому покупець може обрати софу на два чи три місця та підібрати крісла, буфет й тумбу під телевізор, які до неї пасуватимуть. Сучасний скандинавський стиль створює інтерактивний та живий простір для життя. Ви можете прочитати про хитрощі оформлення залу з мінімальними витратами у нашому блозі.",
    imageUrl: require("../../assets/livingroom/livingroom.jpg"),
    shelves: [...shelves],
    chairs: [...chairs],
    tables: [
      {
        id: 59,
        name: "Столик RANDERUP д.47 см чорний",
        subCategoryName: "Столики",
        price: 550,
        imageUrl: require("../../assets/livingroom/tables/tables1.jpg"),
        checked: false,
      },
      {
        id: 60,
        name: "Столик NYBO д.55см дуб/чорний",
        subCategoryName: "Столики",
        price: 1299,
        imageUrl: require("../../assets/livingroom/tables/tables2.jpg"),
        checked: false,
      },
      {
        id: 61,
        name: "Столик OSTED 45x45см 1пол бамбук",
        subCategoryName: "Столики",
        price: 1850,
        imageUrl: require("../../assets/livingroom/tables/tables3.jpg"),
        checked: false,
      },
      {
        id: 62,
        name: "Стіл кавовий DOKKEDAL 75х115 см бетон",
        subCategoryName: "Столики",
        price: 4499,
        imageUrl: require("../../assets/livingroom/tables/tables4.jpg"),
        checked: false,
      },
    ],
    sofas: [
      {
        id: 63,
        name: "Софа GISTRUP 2-місна т.синій",
        subCategoryName: "Софи",
        price: 10000,
        imageUrl: require("../../assets/livingroom/sofas/sofas1.jpg"),
        checked: false,
      },
      {
        id: 64,
        name: "Софа DAMHALE 3-місна чорний",
        subCategoryName: "Софи",
        price: 13500,
        imageUrl: require("../../assets/livingroom/sofas/sofas2.jpg"),
        checked: false,
      },
      {
        id: 65,
        name: "Софа GEDVED 2-місна сірий",
        subCategoryName: "Софи",
        price: 11500,
        imageUrl: require("../../assets/livingroom/sofas/sofas3.jpg"),
        checked: false,
      },
      {
        id: 66,
        name: "Софа кутова SVALBARD т.сірий",
        subCategoryName: "Софи",
        price: 18500,
        imageUrl: require("../../assets/livingroom/sofas/sofas4.jpg"),
        checked: false,
      },
    ],
    buffets: [...buffets],
    //add more sub categories
  },
  diningRoom: {
    categoryName: "Кухня та їдальня",
    categoryTitle:
      "Меблі для кухні - обідні столи, стільці, лави, буфети, консольні столики",
    categoryDescription:
      "Неважливо, якого розміру у вас кухня! Навіть у маленькій кімнаті можна розмістити невеликий кухонний набір та необхідну техніку. Допоможуть складані меблі, барні ергономічні столи та серванти з великими глибокими полицями, або стильна етажерка. Кухонні меблі, представлені в асортименті, виконані у скандинавському стилі та підійдуть до будь-якого дизайну. Класика, модерн, лофт, прованс, ретро - ми допоможемо підібрати меблі як в маленьку кухню, так й простору їдальню. Поставити кухонний набір з розкладним столом в обідній зоні або барний стілець на балконі? Вибирайте те, що вам до вподоби, додайте витончені фіранки, кухонні рушники, посуд та стильні керамічні вироби з нової колекції для створення затишку. А в блогах ви можете знайти ідеї для втілення на власній кухні, адже там є безліч практичних порад, прикладів розташування меблів та скандинавського дизайну кухні. ",
    imageUrl: require("../../assets/diningroom/diningroom.jpg"),
    chairs: [...chairs],
    buffets: [...buffets],
    shelves: [...shelves],
  },
  storage: {
    categoryName: "Зберігання",
    categoryTitle: "Великий асортимент меблів для зберігання речей",
    categoryDescription:
      "Ми вважаємо, що зберігання речей має бути стильним. Оскільки простір стає дедалі ціннішим, недоцільно забивати горища або підвали картонними коробками. Шафи, комоди, стелажі, кошики, лави, вішалки, полиці... Ми добре розуміємо потреби клієнтів. Саме тому наші рішення зі зберігання речей не захаращуватимуть простір та не вимагатимуть від вас прибрати все зайве, аби зробити домівку гарним місцем для мешкання. Меблі у скандинавському стилі вирізняються якістю та лаконічним дизайном. Для передпокою ми зібрали найкращі варіанти банкеток, лав, готових наборів з гачками, дзеркалом та полицями. На сайті можна знайти як перевірені іншими покупцями товари, що мають більше ніж 200 відгуків, так й новинки. Також ми оновили асортимент вішалок, у тому числі якісні пересувні вішалки на коліщатах, які завжди мають попит. Для зручного зберігання сезонних речей, дитячих іграшок, в асортименті є зручні пластикові органайзери різних розмірів та гарні плетені кошики для дрібниць.",
    imageUrl: require("../../assets/storage/storage.jpg"),
    buffets: [...buffets],
    shelves: [...shelves],
    wardrobes: [...wardrobes],
    //add more sub categories
  },
  windows: {
    categoryName: "Для вікон",
    categoryTitle:
      "Оформлення кімнати: великий вибір штор, ролет та аксесуарів",
    categoryDescription:
      "В першу чергу, нові штори треба вибрати зважаючи на загальний дизайн кімнати. Прозорі та напівпрозорі прикрашають кімнату та додають інтер'єру завершеності, а блекаут (сонцезахисні) - надійно захищають від сонячного світла. Прості прямі штори або штори-плісе - які, на вашу думку, краще впишуться в інтер'єр вашої кімнати? Ми пропонуємо широкий вибір штор будь-якого кольору та довжини. Штори для кухні, вітальні та спальні. Додайте до своїх нових штор стильні аксесуари та насолоджуйтесь оновленим інтер'єром, адже саме штори, фіранки та ролети додають настрою та слугують завершальним акцентом в облаштуванні кімнати. У нас можна придбати сучасні ролети, фіранки та рулонні штори для всіх кімнат. Асортимент штор, жалюзі та аксесуарів для вікон можна переглянути онлайн в інтернет-магазині JYSK.ua та в будь-якому магазині мережі JYSK в Україні.",
    imageUrl: require("../../assets/windows/windows.jpg"),
    accessories: [
      {
        id: 71,
        name: "Кільця для фіранок з гачками 10 шт/упак.",
        subCategoryName: "Аксесуари",
        price: 150,
        imageUrl: require("../../assets/windows/accessories/accessories1.jpg"),
        checked: false,
      },
      {
        id: 72,
        name: "Карниз подвійний BALL 120-210см",
        subCategoryName: "Аксесуари",
        price: 1650,
        imageUrl: require("../../assets/windows/accessories/accessories2.jpg"),
        checked: false,
      },
      {
        id: 73,
        name: "Кліпси для фіранок чорний мат 10шт/упак.",
        subCategoryName: "Аксесуари",
        price: 135,
        imageUrl: require("../../assets/windows/accessories/accessories3.jpg"),
        checked: false,
      },
      {
        id: 74,
        name: "Тримач д/фіранок HVASSER чорний",
        subCategoryName: "Аксесуари",
        price: 250,
        imageUrl: require("../../assets/windows/accessories/accessories4.jpg"),
        checked: false,
      },
    ],
    curtains: [
      {
        id: 75,
        name: "Фіранка ISTEREN 1x140x300 св.сірий",
        subCategoryName: "Штори",
        price: 550,
        imageUrl: require("../../assets/windows/curtains/curtains1.jpg"),
        checked: false,
      },
      {
        id: 76,
        name: "Фіранка AUSTRA 1x140x300 оксамит бежевий",
        subCategoryName: "Штори",
        price: 1499,
        imageUrl: require("../../assets/windows/curtains/curtains2.jpg"),
        checked: false,
      },
      {
        id: 77,
        name: "Фіранка RUSKEN 1х140x300 меланж світло-сірий",
        subCategoryName: "Штори",
        price: 999,
        imageUrl: require("../../assets/windows/curtains/curtains3.jpg"),
        checked: false,
      },
      {
        id: 78,
        name: "Фіранка ANTEN 1х140x300 шт.замш оливк.",
        subCategoryName: "Штори",
        price: 1499,
        imageUrl: require("../../assets/windows/curtains/curtains4.jpg"),
        checked: false,
      },
    ],
    rollerBlinds: [
      {
        id: 79,
        name: "Ролета блекаут BOLGA 100x170см с.сірий",
        subCategoryName: "Ролети",
        price: 1299,
        imageUrl: require("../../assets/windows/rollerBlinds/rollerBlinds1.jpg"),
        checked: false,
      },
      {
        id: 80,
        name: "Ролета SENJA 45x170см пісочний",
        subCategoryName: "Ролети",
        price: 499,
        imageUrl: require("../../assets/windows/rollerBlinds/rollerBlinds2.jpg"),
        checked: false,
      },
      {
        id: 81,
        name: "Ролета день-ніч FEMRIS 45x180см тауп",
        subCategoryName: "Ролети",
        price: 699,
        imageUrl: require("../../assets/windows/rollerBlinds/rollerBlinds3.jpg"),
        checked: false,
      },
      {
        id: 82,
        name: "Ролета день-ніч FEMRIS 45x180см сірий",
        subCategoryName: "Ролети",
        price: 699,
        imageUrl: require("../../assets/windows/rollerBlinds/rollerBlinds4.jpg"),
        checked: false,
      },
    ],
    //add more sub categories
  },
  garden: {
    categoryName: "Для саду",
    categoryTitle:
      "Садові меблі - все для саду, дачі, туризму та літнього відпочинку",
    categoryDescription:
      "У весняно-літньому сезоні 2023 представлений оновлений асортимент класичних садових меблів з різних матеріалів: твердої деревини, петана, ротанга, металу, алюмінію та пластику. Палатки, крісла, шезлонги, тенти, пуфи, гамаки, літні намети, павільйони, набори садових меблів, лаунж сети - ви знайдете все для свого дозвілля в JYSK. Парасолі на пляж, туристичний намет, надувні матраци, шезлонги, батут, лед світильники на сонячних батареях, вуличне освітлення, складані крісла для рибалки, сумки-холодильники, обігрівачі, розважальні рухливі ігри для діток та дорослих! Якісні садові меблі для дачі, подвір'я та саду, горщики для квітів та декор - неодмінні атрибути для створення атмосфери та якісного відпочинку на свіжому повітрі. У вас є балкон чи ви бажаєте оновити дизайн літньої тераси? Маємо безліч чудових варіантів для облаштування невеликого простору та розкішного патіо. Онлайн-асортимент ширший за виставки в магазинах, тож вибирайте те, що вам до вподоби вже зараз!",
    imageUrl: require("../../assets/garden/garden.jpg"),
    loungeNetworks: [
      {
        id: 83,
        name: "Комплект меблів для відпочинку VASTO 4м білий",
        subCategoryName: "Лаунж сети",
        price: 26500,
        imageUrl: require("../../assets/garden/loungeNetworks/loungeNetworks1.jpg"),
        checked: false,
      },
      {
        id: 84,
        name: "Комплект меблів для відпочинку BEJSTRUP 4м сірий",
        subCategoryName: "Лаунж сети",
        price: 39999,
        imageUrl: require("../../assets/garden/loungeNetworks/loungeNetworks2.jpg"),
        checked: false,
      },
      {
        id: 85,
        name: "Комплект меблів для відпочинку модульний EG 6м чорний",
        subCategoryName: "Лаунж сети",
        price: 32500,
        imageUrl: require("../../assets/garden/loungeNetworks/loungeNetworks3.jpg"),
        checked: false,
      },
      {
        id: 86,
        name: "Комплект меблів для відпочинку ULLEHUSE з ємністю 9м чорний",
        subCategoryName: "Лаунж сети",
        price: 59999,
        imageUrl: require("../../assets/garden/loungeNetworks/loungeNetworks4.jpg"),
        checked: false,
      },
    ],
    chairs: [
      {
        id: 87,
        name: "Стілець багатопозиційний KAMSTRUP хард.",
        subCategoryName: "Стільці для відпочинку",
        price: 3500,
        imageUrl: require("../../assets/garden/chairs/chairs1.jpg"),
        checked: false,
      },
      {
        id: 88,
        name: "Стілець садовий GRENAA чорний/сірий",
        subCategoryName: "Стільці для відпочинку",
        price: 900,
        imageUrl: require("../../assets/garden/chairs/chairs2.jpg"),
        checked: false,
      },
      {
        id: 89,
        name: "Стілець садовий ILDERHUSE чорний",
        subCategoryName: "Стільці для відпочинку",
        price: 3999,
        imageUrl: require("../../assets/garden/chairs/chairs3.jpg"),
        checked: false,
      },
      {
        id: 90,
        name: "Стілець BREDSTEN 6-позиційний чорний",
        subCategoryName: "Стільці для відпочинку",
        price: 4699,
        imageUrl: require("../../assets/garden/chairs/chairs4.jpg"),
        checked: false,
      },
    ],
    tables: [
      {
        id: 91,
        name: "Стіл садовий JERSORE 80х140см чорний",
        subCategoryName: "Садові столи",
        price: 5000,
        imageUrl: require("../../assets/garden/tables/tables1.jpg"),
        checked: false,
      },
      {
        id: 92,
        name: "Стіл RANGSTRUP д.130см натуральний/чорний",
        subCategoryName: "Садові столи",
        price: 10000,
        imageUrl: require("../../assets/garden/tables/tables2.jpg"),
        checked: false,
      },
      {
        id: 93,
        name: "Стіл садовий GAMMELBY 100х225см сірий",
        subCategoryName: "Садові столи",
        price: 29999,
        imageUrl: require("../../assets/garden/tables/tables3.jpg"),
        checked: false,
      },
      {
        id: 94,
        name: "Стіл садовий HOLTE діам.120см хардвуд",
        subCategoryName: "Садові столи",
        price: 13500,
        imageUrl: require("../../assets/garden/tables/tables4.jpg"),
        checked: false,
      },
    ],
    storage: [
      {
        id: 95,
        name: "Короб TAMBOHUSE 150х77х91см сірий",
        subCategoryName: "Вуличне зберігання",
        price: 16500,
        imageUrl: require("../../assets/garden/storage/storage1.jpg"),
        checked: false,
      },
      {
        id: 96,
        name: "Короб для подушок TAMBOHUSE 150х77х91см натуральний",
        subCategoryName: "Вуличне зберігання",
        price: 16500,
        imageUrl: require("../../assets/garden/storage/storage2.jpg"),
        checked: false,
      },
      {
        id: 97,
        name: "Короб KRAMNITSE 132х72х114см сірий",
        subCategoryName: "Вуличне зберігання",
        price: 9999,
        imageUrl: require("../../assets/garden/storage/storage3.jpg"),
        checked: false,
      },
      {
        id: 98,
        name: "Короб для подушок BERGEN 197x76x71см чорний",
        subCategoryName: "Вуличне зберігання",
        price: 10000,
        imageUrl: require("../../assets/garden/storage/storage4.jpg"),
        checked: false,
      },
    ],
    //add more sub categories
  },
  forHome: {
    categoryName: "Для дому",
    categoryTitle:
      "Товари для дому – все для створення затишної атмосфери у вашій оселі",
    categoryDescription:
      "Ви цікавитесь дизайном інтер'єру, новими трендами та бажаєте дізнатися більше про скандинавський стиль? В JYSK ми хотіли б допомогти вам в оформленні інтер'єру. Ми постійно працюємо з кількома трендами, які ретельно відбираються командою наших дизайнерів. На сайті або в магазині ви знайдете все, що шукаєте: і цікаві рамки для фотографій, і скатертину для обіднього столу, і декоративні подушки на диван. Ми можемо задовольнити будь-які потреби. Товари для оселі стануть гарним подарунком, ми допоможемо підібрати саме те, що буде вам до вподоби! Теплі пухнасті пледи створюють чарівну атмосферу затишку, стильний декор додає інтер'єру скандинавського настрою, а незвичне освітлення підкреслює індивідуальність. Як відчути хюґе? Розкриваємо секрети у блозі.",
    imageUrl: require("../../assets/forHome/forHome.jpg"),
    mirrors: [...mirrors],
    childrenFurniture: [
      {
        id: 99,
        name: "Крісло-мішок SNEKKERSTEN 60х90х60см",
        subCategoryName: "Дитячі меблі",
        price: 1350,
        imageUrl: require("../../assets/forHome/childrenFurniture/childrenFurniture1.jpg"),
        checked: false,
      },
      {
        id: 100,
        name: "Намет ігровий SMINGE 120х148см зірки",
        subCategoryName: "Дитячі меблі",
        price: 1399,
        imageUrl: require("../../assets/forHome/childrenFurniture/childrenFurniture2.jpg"),
        checked: false,
      },
      {
        id: 101,
        name: "Захисний бар'єр для дітей SALENE білий",
        subCategoryName: "Дитячі меблі",
        price: 2500,
        imageUrl: require("../../assets/forHome/childrenFurniture/childrenFurniture3.jpg"),
        checked: false,
      },
      {
        id: 102,
        name: "Крісло-ліжко VEGGER сірий",
        subCategoryName: "Дитячі меблі",
        price: 5500,
        imageUrl: require("../../assets/forHome/childrenFurniture/childrenFurniture4.jpg"),
        checked: false,
      },
    ],
    blankets: [
      {
        id: 103,
        name: "Плед KASTANJ 130x170см фліс білий/сірий",
        subCategoryName: "Пледи",
        price: 200,
        imageUrl: require("../../assets/forHome/blankets/blankets1.jpg"),
        checked: false,
      },
      {
        id: 104,
        name: "Плед BONDEROSE 130x170см латте",
        subCategoryName: "Пледи",
        price: 425,
        imageUrl: require("../../assets/forHome/blankets/blankets2.jpg"),
        checked: false,
      },
      {
        id: 105,
        name: "Плед стьобаний SKOVSTJERNE 140x200см білий/синій",
        subCategoryName: "Пледи",
        price: 500,
        imageUrl: require("../../assets/forHome/blankets/blankets3.jpg"),
        checked: false,
      },
      {
        id: 106,
        name: "Плед LUNDKARSE 130x170см вовна сірий/беж",
        subCategoryName: "Пледи",
        price: 1500,
        imageUrl: require("../../assets/forHome/blankets/blankets4.jpg"),
        checked: false,
      },
    ],
    pillows: [
      {
        id: 107,
        name: "Подушка ASPARGES 40x40см асорт.",
        subCategoryName: "Декоративні подушки",
        price: 100,
        imageUrl: require("../../assets/forHome/pillows/pillows1.jpg"),
        checked: false,
      },
      {
        id: 108,
        name: "Подушка FRESIA 35x50см зелений/синій",
        subCategoryName: "Декоративні подушки",
        price: 225,
        imageUrl: require("../../assets/forHome/pillows/pillows2.jpg"),
        checked: false,
      },
      {
        id: 109,
        name: "Подушка HORNFIOL шеніль 45x45см синій",
        subCategoryName: "Декоративні подушки",
        price: 425,
        imageUrl: require("../../assets/forHome/pillows/pillows3.jpg"),
        checked: false,
      },
      {
        id: 110,
        name: "Подушка LILJE 35х50см велюр сірий",
        subCategoryName: "Декоративні подушки",
        price: 325,
        imageUrl: require("../../assets/forHome/pillows/pillows4.jpg"),
        checked: false,
      },
    ],
    //add more sub categories
  },

  other: [
    {
      id: 111,
      name: "Подушка ASPARGES 40x40см асорт.",
      subCategoryName: "Декоративні подушки",
      price: 100,
    },
  ],
};

export default function ProductProvider({ children }) {
  const [products, setProducts] = useState(productState);

  return (
    <ProductContext.Provider value={{ products, setProducts }}>
      {children}
    </ProductContext.Provider>
  );
}
