import React, { createContext, useState } from "react";
export const ProductContext = createContext();

const wardrobes = [
  {
    id: 1,
    name: "Шафа HAGENDRUP 96x176см комбі білий",
    subCategoryName: "Шафи",
    price: 5500,
    imageUrl: require("../../assets/bedroom/wardrobes/wardrobes1.jpg"),
    checked: false,
  },
  {
    id: 2,
    name: "Шафа HAGENDRUP 3дв 3шух дуб",
    subCategoryName: "Шафи",
    price: 7500,
    imageUrl: require("../../assets/bedroom/wardrobes/wardrobes2.jpg"),
    checked: false,
  },
  {
    id: 3,
    name: "Шафа BILLUND 2дв 2шух білий/бетон",
    subCategoryName: "Шафи",
    price: 5500,
    imageUrl: require("../../assets/bedroom/wardrobes/wardrobes3.jpg"),
    checked: false,
  },
  {
    id: 4,
    name: "Шафа JENSLEV 145x176см дуб",
    subCategoryName: "Шафи",
    price: 8500,
    imageUrl: require("../../assets/bedroom/wardrobes/wardrobes4.jpg"),
    checked: false,
  },
  {
    id: 5,
    name: "Шафа VELLERUP 200х200см комбі дуб",
    subCategoryName: "Шафи",
    price: 13500,
    imageUrl: require("../../assets/bedroom/wardrobes/wardrobes5.jpg"),
    checked: false,
  },
];
const mirrors = [
  {
    id: 1,
    name: "Дзеркало MARSTAL д.70см чорний",
    subCategoryName: "Дзеркала",
    price: 1500,
    imageUrl: require("../../assets/bedroom/mirrors/mirrors1.jpg"),
    checked: false,
  },
  {
    id: 2,
    name: "Дзеркало BALSLEV 35x127см білий",
    subCategoryName: "Дзеркала",
    price: 1000,
    imageUrl: require("../../assets/bedroom/mirrors/mirrors2.jpg"),
    checked: false,
  },
  {
    id: 3,
    name: "Дзеркало SPANG 40x70см чорний",
    subCategoryName: "Дзеркала",
    price: 1000,
    imageUrl: require("../../assets/bedroom/mirrors/mirrors3.jpg"),
    checked: false,
  },
  {
    id: 4,
    name: "Дзеркало NORDBORG 72х162см золотистий",
    subCategoryName: "Дзеркала",
    price: 1750,
    imageUrl: require("../../assets/bedroom/mirrors/mirrors4.jpg"),
    checked: false,
  },
  {
    id: 5,
    name: "Дзеркало STUDSTRUP 80x180см чорний",
    subCategoryName: "Дзеркала",
    price: 5000,
    imageUrl: require("../../assets/bedroom/mirrors/mirrors5.jpg"),
    checked: false,
  },
];
const shelves = [
  {
    id: 1,
    name: "Стелаж VANDBORG 3пол дуб/чорний",
    subCategoryName: "Книжкові шафи, стелажі",
    price: 1750,
    imageUrl: require("../../assets/office/shelves/shelves1.jpg"),
    checked: false,
  },
  {
    id: 2,
    name: "Стелаж TRAPPEDAL 5пол дуб/білий",
    subCategoryName: "Книжкові шафи, стелажі",
    price: 2350,
    imageUrl: require("../../assets/office/shelves/shelves2.jpg"),
    checked: false,
  },
  {
    id: 3,
    name: "Шафка SKALS 2дв дуб",
    subCategoryName: "Книжкові шафи, стелажі",
    price: 3000,
    imageUrl: require("../../assets/office/shelves/shelves3.jpg"),
    checked: false,
  },
  {
    id: 4,
    name: "Шафка SKALS 2дв білий",
    subCategoryName: "Книжкові шафи, стелажі",
    price: 2750,
    imageUrl: require("../../assets/office/shelves/shelves4.jpg"),
    checked: false,
  },
];
const chairs = [
  {
    id: 1,
    name: "Стілець обідній JONSTRUP сірий/дуб",
    subCategoryName: "Стільці",
    price: 1350,
    imageUrl: require("../../assets/diningroom/chairs/chair1.jpg"),
    checked: false,
  },
  {
    id: 2,
    name: "Стілець обідній EJSTRUP синій/сталь",
    subCategoryName: "Стільці",
    price: 1650,
    imageUrl: require("../../assets/diningroom/chairs/chair2.jpg"),
    checked: false,
  },
  {
    id: 3,
    name: "Стілець обідній TUREBY беж тканина",
    subCategoryName: "Стільці",
    price: 2000,
    imageUrl: require("../../assets/diningroom/chairs/chair3.jpg"),
    checked: false,
  },
  {
    id: 4,
    name: "Стілець обідній KOKKEDAL сірий/дуб",
    subCategoryName: "Стільці",
    price: 1850,
    imageUrl: require("../../assets/diningroom/chairs/chair4.jpg"),
    checked: false,
  },
  {
    id: 5,
    name: "Стілець обідній TOREBY шт.шкіра чорний",
    subCategoryName: "Стільці",
    price: 1000,
    imageUrl: require("../../assets/diningroom/chairs/chair5.jpg"),
    checked: false,
  },
  {
    id: 6,
    name: "Стілець обідній GADSTRUP чорний дуб",
    subCategoryName: "Стільці",
    price: 1000,
    imageUrl: require("../../assets/diningroom/chairs/chair6.jpg"),
    checked: false,
  },
  {
    id: 7,
    name: "Стілець обідній TYLSTRUP кавовий",
    subCategoryName: "Стільці",
    price: 1350,
    imageUrl: require("../../assets/diningroom/chairs/chair7.jpg"),
    checked: false,
  },
  {
    id: 8,
    name: "Стілець обідній JEGIND натура/білий",
    subCategoryName: "Стільці",
    price: 2000,
    imageUrl: require("../../assets/diningroom/chairs/chair8.jpg"),
    checked: false,
  },
];
const buffets = [
  {
    id: 1,
    name: "Буфет JENSLEV 2дв 4шух дуб/білий",
    subCategoryName: "Буфети",
    price: 5000,
    imageUrl: require("../../assets/livingroom/buffets/buffets1.jpg"),
    checked: false,
  },
  {
    id: 2,
    name: "Буфет SKOVLUNDE 2дв 3шух натур. дуб/чорний",
    subCategoryName: "Буфети",
    price: 9000,
    imageUrl: require("../../assets/livingroom/buffets/buffets2.jpg"),
    checked: false,
  },
  {
    id: 3,
    name: "Буфет-сервант MARKSKEL білий/дуб",
    subCategoryName: "Буфети",
    price: 21998,
    imageUrl: require("../../assets/livingroom/buffets/buffets3.jpg"),
    checked: false,
  },
  {
    id: 4,
    name: "Буфет MANDERUP 3дв 3шух дикий дуб",
    subCategoryName: "Буфети",
    price: 11999,
    imageUrl: require("../../assets/livingroom/buffets/buffets4.jpg"),
    checked: false,
  },
];
const productState = {
  bedroom: {
    categoryName: "Спальня",
    imageUrl: require("../../assets/bedroom/bedroom.jpg"),
    accessories: [
      {
        id: 1,
        name: "Ніжки для ламельної основи 4шт. д.5см в.23см сталь",
        subCategoryName: "Аксесуари",
        price: 400,
        imageUrl: require("../../assets/bedroom/accessories/accessories1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Вставка між матрацами д.195см DREAMZONE",
        subCategoryName: "Аксесуари",
        price: 500,
        imageUrl: require("../../assets/bedroom/accessories/accessories2.jpg"),
        checked: false,
      },
    ],
    beds: [
      {
        id: 1,
        name: "Ліжко KILDEN 90x200см темно-сірий",
        subCategoryName: "Ліжка",
        price: 4500,
        imageUrl: require("../../assets/bedroom/beds/beds1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Ліжко SALLINGE 140x200см натура",
        subCategoryName: "Ліжка",
        price: 5250,
        imageUrl: require("../../assets/bedroom/beds/beds2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Ліжко VEDDE 140x200см дикий дуб",
        subCategoryName: "Ліжка",
        price: 6250,
        imageUrl: require("../../assets/bedroom/beds/beds3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "ЛЛіжко KONGSBERG 140x200см сірий",
        subCategoryName: "Ліжка",
        price: 8000,
        imageUrl: require("../../assets/bedroom/beds/beds4.jpg"),
        checked: false,
      },
      {
        id: 5,
        name: "Ліжко HASLEV 140x200см т.сірий",
        subCategoryName: "Ліжка",
        price: 11500,
        imageUrl: require("../../assets/bedroom/beds/beds5.jpg"),
        checked: false,
      },
    ],
    pillows: [
      {
        id: 1,
        name: "Подушка BEITO 50x70см 850г",
        subCategoryName: "Подушки",
        price: 1100,
        imageUrl: require("../../assets/bedroom/pillows/pillows1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Подушка ROMEDAL 50x70см 900г",
        subCategoryName: "Подушки",
        price: 375,
        imageUrl: require("../../assets/bedroom/pillows/pillows2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Подушка ROMEDAL висока 50x70см 1100г",
        subCategoryName: "Подушки",
        price: 550,
        imageUrl: require("../../assets/bedroom/pillows/pillows3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Подушка STEINKOLLEN 50х70см 1050г",
        subCategoryName: "Подушки",
        price: 400,
        imageUrl: require("../../assets/bedroom/pillows/pillows4.jpg"),
        checked: false,
      },
      {
        id: 5,
        name: "Подушка FALKETIND 750г 50x70см",
        subCategoryName: "Подушки",
        price: 850,
        imageUrl: require("../../assets/bedroom/pillows/pillows5.jpg"),
        checked: false,
      },
    ],
    mirrors: [...mirrors],
    wardrobes: [...wardrobes],
    //add more sub categories
  },
  bathroom: {
    categoryName: "Ванна",
    imageUrl: require("../../assets/bathroom/bathroom.jpg"),
    accessories: [
      {
        id: 1,
        name: "Склянка для щіток ESSVIK перероблене скло",
        subCategoryName: "Аксесуари",
        price: 115,
        imageUrl: require("../../assets/bathroom/accessories/accessories1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Відро VEGBY 5 л морські водорості",
        subCategoryName: "Аксесуари",
        price: 700,
        imageUrl: require("../../assets/bathroom/accessories/accessories2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Полиця NACKA з гачками чорний",
        subCategoryName: "Аксесуари",
        price: 800,
        imageUrl: require("../../assets/bathroom/accessories/accessories3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Диспенсер для мила ROSENLUND асорт.",
        subCategoryName: "Аксесуари",
        price: 90,
        imageUrl: require("../../assets/bathroom/accessories/accessories4.jpg"),
        checked: false,
      },
    ],
    towels: [
      {
        id: 1,
        name: "Рушник FLISBY 40x60см білий",
        subCategoryName: "Рушники",
        price: 35,
        imageUrl: require("../../assets/bathroom/towels/towels1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Рушник TORSBY 50x90см сірий",
        subCategoryName: "Рушники",
        price: 100,
        imageUrl: require("../../assets/bathroom/towels/towels2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Рушник YSBY 50x90см рожевий",
        subCategoryName: "Рушники",
        price: 135,
        imageUrl: require("../../assets/bathroom/towels/towels3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Рушник MALUNG 50x100см беж",
        subCategoryName: "Рушники",
        price: 160,
        imageUrl: require("../../assets/bathroom/towels/towels4.jpg"),
        checked: false,
      },
    ],
    mirrors: [...mirrors],
    bathrobes: [
      {
        id: 1,
        name: "Халат NITTA S/M мікрофібра білий",
        subCategoryName: "Халати та капці",
        price: 550,
        imageUrl: require("../../assets/bathroom/bathrobes/bathrobes1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Халат VALBO L/XL т.синій",
        subCategoryName: "Халати та капці",
        price: 500,
        imageUrl: require("../../assets/bathroom/bathrobes/bathrobes2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Капці BROKIND р.36-46 в асортименті",
        subCategoryName: "Халати та капці",
        price: 450,
        imageUrl: require("../../assets/bathroom/bathrobes/bathrobes3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Сандалі LAXVIK 35-42 асорт.",
        subCategoryName: "Халати та капці",
        price: 475,
        imageUrl: require("../../assets/bathroom/bathrobes/bathrobes4.jpg"),
        checked: false,
      },
    ],
    //add more sub categories
  },
  office: {
    categoryName: "Офіс",
    imageUrl: require("../../assets/office/office.jpg"),
    accessories: [
      {
        id: 1,
        name: "Підставка для ноутбука THEM бамбук",
        subCategoryName: "Аксесуари",
        price: 1000,
        imageUrl: require("../../assets/office/accessories/accessories1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Підставка для ноутбука MEJLBY регульована чорний",
        subCategoryName: "Аксесуари",
        price: 750,
        imageUrl: require("../../assets/office/accessories/accessories2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Підставка для ноутбука NEJRUP асорт.",
        subCategoryName: "Аксесуари",
        price: 450,
        imageUrl: require("../../assets/office/accessories/accessories3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Підставка для монітора SULDRUP чорний",
        subCategoryName: "Аксесуари",
        price: 700,
        imageUrl: require("../../assets/office/accessories/accessories4.jpg"),
        checked: false,
      },
    ],
    officeChairs: [
      {
        id: 1,
        name: "Крісло офісне BILLUM чорний",
        subCategoryName: "Крісла офісні",
        price: 2650,
        imageUrl: require("../../assets/office/chairs/chairs1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Крісло офісне SKODSBORG сірий",
        subCategoryName: "Крісла офісні",
        price: 4000,
        imageUrl: require("../../assets/office/chairs/chairs2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Крісло офісне KASTBJERG шт.шкіра чорний",
        subCategoryName: "Крісла офісні",
        price: 5500,
        imageUrl: require("../../assets/office/chairs/chairs3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Крісло офісне ABILDHOLT т.сірий/хром",
        subCategoryName: "Крісла офісні",
        price: 2650,
        imageUrl: require("../../assets/office/chairs/chairs4.jpg"),
        checked: false,
      },
    ],
    tables: [
      {
        id: 1,
        name: "Стіл письмовий VANDBORG 60х120 дуб/чорн.",
        subCategoryName: "Комп'ютерні та письмові столи",
        price: 1500,
        imageUrl: require("../../assets/office/tables/tables1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Стіл геймерський HALSTED 60х120см чорний",
        subCategoryName: "Комп'ютерні та письмові столи",
        price: 2250,
        imageUrl: require("../../assets/office/tables/tables2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Стіл письмовий BILLUND 53х120 білий/дуб",
        subCategoryName: "Комп'ютерні та письмові столи",
        price: 3000,
        imageUrl: require("../../assets/office/tables/tables3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Стіл письмовий EVETOFTE дуб",
        subCategoryName: "Комп'ютерні та письмові столи",
        price: 3750,
        imageUrl: require("../../assets/office/tables/tables4.jpg"),
        checked: false,
      },
    ],
    shelves: [...shelves],
    //add more sub categories
  },
  livingroom: {
    categoryName: "Вітальня",
    imageUrl: require("../../assets/livingroom/livingroom.jpg"),
    shelves: [...shelves],
    chairs: [...chairs],
    tables: [
      {
        id: 1,
        name: "Столик RANDERUP д.47 см чорний",
        subCategoryName: "Столики",
        price: 550,
        imageUrl: require("../../assets/livingroom/tables/tables1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Столик NYBO д.55см дуб/чорний",
        subCategoryName: "Столики",
        price: 1299,
        imageUrl: require("../../assets/livingroom/tables/tables2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Столик OSTED 45x45см 1пол бамбук",
        subCategoryName: "Столики",
        price: 1850,
        imageUrl: require("../../assets/livingroom/tables/tables3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Стіл кавовий DOKKEDAL 75х115 см бетон",
        subCategoryName: "Столики",
        price: 4499,
        imageUrl: require("../../assets/livingroom/tables/tables4.jpg"),
        checked: false,
      },
    ],
    sofas: [
      {
        id: 1,
        name: "Софа GISTRUP 2-місна т.синій",
        subCategoryName: "Софи",
        price: 10000,
        imageUrl: require("../../assets/livingroom/sofas/sofas1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Софа DAMHALE 3-місна чорний",
        subCategoryName: "Софи",
        price: 13500,
        imageUrl: require("../../assets/livingroom/sofas/sofas2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Софа GEDVED 2-місна сірий",
        subCategoryName: "Софи",
        price: 11500,
        imageUrl: require("../../assets/livingroom/sofas/sofas3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Софа кутова SVALBARD т.сірий",
        subCategoryName: "Софи",
        price: 18500,
        imageUrl: require("../../assets/livingroom/sofas/sofas4.jpg"),
        checked: false,
      },
    ],
    buffets: [...buffets],
    //add more sub categories
  },
  diningRoom: {
    categoryName: "Кухня та їдальня",
    imageUrl: require("../../assets/diningroom/diningroom.jpg"),
    chairs: [...chairs],
    buffets: [...buffets],
    shelves: [...shelves],
  },
  storage: {
    categoryName: "Зберігання",
    imageUrl: require("../../assets/storage/storage.jpg"),
    buffets: [...buffets],
    shelves: [...shelves],
    wardrobes: [...wardrobes],
    //add more sub categories
  },
  windows: {
    categoryName: "Для вікон",
    imageUrl: require("../../assets/windows/windows.jpg"),
    accessories: [
      {
        id: 1,
        name: "Кільця для фіранок з гачками 10 шт/упак.",
        subCategoryName: "Аксесуари для штор",
        price: 150,
        imageUrl: require("../../assets/windows/accessories/accessories1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Карниз подвійний BALL 120-210см",
        subCategoryName: "Аксесуари для штор",
        price: 1650,
        imageUrl: require("../../assets/windows/accessories/accessories2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Кліпси для фіранок чорний мат 10шт/упак.",
        subCategoryName: "Аксесуари для штор",
        price: 135,
        imageUrl: require("../../assets/windows/accessories/accessories3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Тримач д/фіранок HVASSER чорний",
        subCategoryName: "Аксесуари для штор",
        price: 250,
        imageUrl: require("../../assets/windows/accessories/accessories4.jpg"),
        checked: false,
      },
    ],
    curtains: [
      {
        id: 1,
        name: "Фіранка ISTEREN 1x140x300 св.сірий",
        subCategoryName: "Штори",
        price: 550,
        imageUrl: require("../../assets/windows/curtains/curtains1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Фіранка AUSTRA 1x140x300 оксамит бежевий",
        subCategoryName: "Штори",
        price: 1499,
        imageUrl: require("../../assets/windows/curtains/curtains2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Фіранка RUSKEN 1х140x300 меланж світло-сірий",
        subCategoryName: "Штори",
        price: 999,
        imageUrl: require("../../assets/windows/curtains/curtains3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Фіранка ANTEN 1х140x300 шт.замш оливк.",
        subCategoryName: "Штори",
        price: 1499,
        imageUrl: require("../../assets/windows/curtains/curtains4.jpg"),
        checked: false,
      },
    ],
    rollerBlinds: [
      {
        id: 1,
        name: "Ролета блекаут BOLGA 100x170см с.сірий",
        subCategoryName: "Ролети",
        price: 1299,
        imageUrl: require("../../assets/windows/rollerBlinds/rollerBlinds1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Ролета SENJA 45x170см пісочний",
        subCategoryName: "Ролети",
        price: 499,
        imageUrl: require("../../assets/windows/rollerBlinds/rollerBlinds2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Ролета день-ніч FEMRIS 45x180см тауп",
        subCategoryName: "Ролети",
        price: 699,
        imageUrl: require("../../assets/windows/rollerBlinds/rollerBlinds3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Ролета день-ніч FEMRIS 45x180см сірий",
        subCategoryName: "Ролети",
        price: 699,
        imageUrl: require("../../assets/windows/rollerBlinds/rollerBlinds4.jpg"),
        checked: false,
      },
    ],
    //add more sub categories
  },
  garden: {
    categoryName: "Для саду",
    imageUrl: require("../../assets/garden/garden.jpg"),
    loungeNetworks: [
      {
        id: 1,
        name: "Комплект меблів для відпочинку VASTO 4м білий",
        subCategoryName: "Лаунж сети",
        price: 26500,
        imageUrl: require("../../assets/garden/loungeNetworks/loungeNetworks1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Комплект меблів для відпочинку BEJSTRUP 4м сірий",
        subCategoryName: "Лаунж сети",
        price: 39999,
        imageUrl: require("../../assets/garden/loungeNetworks/loungeNetworks2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Комплект меблів для відпочинку модульний EG 6м чорний",
        subCategoryName: "Лаунж сети",
        price: 32500,
        imageUrl: require("../../assets/garden/loungeNetworks/loungeNetworks3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Комплект меблів для відпочинку ULLEHUSE з ємністю 9м чорний",
        subCategoryName: "Лаунж сети",
        price: 59999,
        imageUrl: require("../../assets/garden/loungeNetworks/loungeNetworks4.jpg"),
        checked: false,
      },
    ],
    chairs: [
      {
        id: 1,
        name: "Стілець багатопозиційний KAMSTRUP хард.",
        subCategoryName: "Стільці для відпочинку",
        price: 3500,
        imageUrl: require("../../assets/garden/chairs/chairs1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Стілець садовий GRENAA чорний/сірий",
        subCategoryName: "Стільці для відпочинку",
        price: 900,
        imageUrl: require("../../assets/garden/chairs/chairs2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Стілець садовий ILDERHUSE чорний",
        subCategoryName: "Стільці для відпочинку",
        price: 3999,
        imageUrl: require("../../assets/garden/chairs/chairs3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Стілець BREDSTEN 6-позиційний чорний",
        subCategoryName: "Стільці для відпочинку",
        price: 4699,
        imageUrl: require("../../assets/garden/chairs/chairs4.jpg"),
        checked: false,
      },
    ],
    tables: [
      {
        id: 1,
        name: "Стіл садовий JERSORE 80х140см чорний",
        subCategoryName: "Садові столи",
        price: 5000,
        imageUrl: require("../../assets/garden/tables/tables1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Стіл RANGSTRUP д.130см натуральний/чорний",
        subCategoryName: "Садові столи",
        price: 10000,
        imageUrl: require("../../assets/garden/tables/tables2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Стіл садовий GAMMELBY 100х225см сірий",
        subCategoryName: "Садові столи",
        price: 29999,
        imageUrl: require("../../assets/garden/tables/tables3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Стіл садовий HOLTE діам.120см хардвуд",
        subCategoryName: "Садові столи",
        price: 13500,
        imageUrl: require("../../assets/garden/tables/tables4.jpg"),
        checked: false,
      },
    ],
    storage: [
      {
        id: 1,
        name: "Короб TAMBOHUSE 150х77х91см сірий",
        subCategoryName: "Вуличне зберігання",
        price: 16500,
        imageUrl: require("../../assets/garden/storage/storage1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Короб для подушок TAMBOHUSE 150х77х91см натуральний",
        subCategoryName: "Вуличне зберігання",
        price: 16500,
        imageUrl: require("../../assets/garden/storage/storage2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Короб KRAMNITSE 132х72х114см сірий",
        subCategoryName: "Вуличне зберігання",
        price: 9999,
        imageUrl: require("../../assets/garden/storage/storage3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Короб для подушок BERGEN 197x76x71см чорний",
        subCategoryName: "Вуличне зберігання",
        price: 10000,
        imageUrl: require("../../assets/garden/storage/storage4.jpg"),
        checked: false,
      },
    ],
    //add more sub categories
  },
  forHome: {
    categoryName: "Для дому",
    imageUrl: require("../../assets/forHome/forHome.jpg"),
    mirrors: [...mirrors],
    childrenFurniture: [
      {
        id: 1,
        name: "Крісло-мішок SNEKKERSTEN 60х90х60см",
        subCategoryName: "Дитячі меблі",
        price: 1350,
        imageUrl: require("../../assets/forHome/childrenFurniture/childrenFurniture1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Намет ігровий SMINGE 120х148см зірки",
        subCategoryName: "Дитячі меблі",
        price: 1399,
        imageUrl: require("../../assets/forHome/childrenFurniture/childrenFurniture2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Захисний бар'єр для дітей SALENE білий",
        subCategoryName: "Дитячі меблі",
        price: 2500,
        imageUrl: require("../../assets/forHome/childrenFurniture/childrenFurniture3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Крісло-ліжко VEGGER сірий",
        subCategoryName: "Дитячі меблі",
        price: 5500,
        imageUrl: require("../../assets/forHome/childrenFurniture/childrenFurniture4.jpg"),
        checked: false,
      },
    ],
    blankets: [
      {
        id: 1,
        name: "Плед KASTANJ 130x170см фліс білий/сірий",
        subCategoryName: "Пледи",
        price: 200,
        imageUrl: require("../../assets/forHome/blankets/blankets1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Плед BONDEROSE 130x170см латте",
        subCategoryName: "Пледи",
        price: 425,
        imageUrl: require("../../assets/forHome/blankets/blankets2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Плед стьобаний SKOVSTJERNE 140x200см білий/синій",
        subCategoryName: "Пледи",
        price: 500,
        imageUrl: require("../../assets/forHome/blankets/blankets3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Плед LUNDKARSE 130x170см вовна сірий/беж",
        subCategoryName: "Пледи",
        price: 1500,
        imageUrl: require("../../assets/forHome/blankets/blankets4.jpg"),
        checked: false,
      },
    ],
    pillows: [
      {
        id: 1,
        name: "Подушка ASPARGES 40x40см асорт.",
        subCategoryName: "Декоративні подушки",
        price: 100,
        imageUrl: require("../../assets/forHome/pillows/pillows1.jpg"),
        checked: false,
      },
      {
        id: 2,
        name: "Подушка FRESIA 35x50см зелений/синій",
        subCategoryName: "Декоративні подушки",
        price: 225,
        imageUrl: require("../../assets/forHome/pillows/pillows2.jpg"),
        checked: false,
      },
      {
        id: 3,
        name: "Подушка HORNFIOL шеніль 45x45см синій",
        subCategoryName: "Декоративні подушки",
        price: 425,
        imageUrl: require("../../assets/forHome/pillows/pillows3.jpg"),
        checked: false,
      },
      {
        id: 4,
        name: "Подушка LILJE 35х50см велюр сірий",
        subCategoryName: "Декоративні подушки",
        price: 325,
        imageUrl: require("../../assets/forHome/pillows/pillows4.jpg"),
        checked: false,
      },
    ],
    //add more sub categories
  },
};

export default function ProductProvider({ children }) {
  const [products, setProducts] = useState(productState);

  return (
    <ProductContext.Provider value={{ products, setProducts }}>
      {children}
    </ProductContext.Provider>
  );
}
